# Generated by Django 5.0.4 on 2024-04-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accessblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='interest',
            field=models.CharField(choices=[('Artificial Intelligence', 'Ai'), ('Machine Learning', 'Ml'), ('Data Science', 'Ds'), ('Software Engineering', 'Se'), ('Database Management', 'Db'), ('Networks', 'Nw'), ('Web Development', 'Web'), ('Mobile Development', 'Mob'), ('Cyber Security', 'Sec'), ('Internet of Things', 'Iot'), ('Augmented Reality', 'Ar'), ('Virtual Reality', 'Vr'), ('Blockchain', 'Bc'), ('Cloud Computing', 'Cc'), ('Robotics', 'Rob'), ('Business Law', 'Bl'), ('Marketing', 'Mk'), ('Finance', 'Fn'), ('Accounting', 'Ac'), ('Economics', 'Ec'), ('Project Management', 'Pm'), ('Human Resources', 'Hr')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(choices=[('Management Information Systems', 'Mis'), ('Computer Science', 'Cs'), ('Business Administration', 'Ba'), ('Electrical Engineering', 'Ee'), ('Mechanical Engineering', 'Me'), ('Computer Engineering', 'Ce')], max_length=50),
        ),
    ]
