# Generated by Django 5.0.4 on 2024-04-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userinterest_interest_alter_userprofile_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
    ]
