# Generated by Django 5.0.4 on 2024-04-07 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(choices=[('Management Information Systems', 'Mis'), ('Computer Science', 'Cs'), ('Business Administration', 'Ba'), ('Electrical Engineering', 'Ee'), ('Mechanical Engineering', 'Me'), ('Computer Engineering', 'Ce')], max_length=100)),
                ('whatsAppLink', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupScheduledTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('Artificial Intelligence', 'Ai'), ('Machine Learning', 'Ml'), ('Data Science', 'Ds'), ('Software Engineering', 'Se'), ('Database Management', 'Db'), ('Networks', 'Nw'), ('Web Development', 'Web'), ('Mobile Development', 'Mob'), ('Cyber Security', 'Sec'), ('Internet of Things', 'Iot'), ('Augmented Reality', 'Ar'), ('Virtual Reality', 'Vr'), ('Blockchain', 'Bc'), ('Cloud Computing', 'Cc'), ('Robotics', 'Rob'), ('Business Law', 'Bl'), ('Marketing', 'Mk'), ('Finance', 'Fn'), ('Accounting', 'Ac'), ('Economics', 'Ec'), ('Project Management', 'Pm'), ('Human Resources', 'Hr')], max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studygroup')),
            ],
        ),
    ]
